### ISSUE TITLE
Python3 incompatibility?

### ISSUE THREAD

**Issue by gardar** [xezpeleta/Ansible-Proxmox-inventory#10]
I'm running into issues running this script from Archlinux and if I'm not mistaken the problem can be traced back to Arch defaulting to python3 rather than python2. (/usr/bin/python being linked to python3).

Running proxmox.py with python3 results in the following error:

`
 Traceback (most recent call last):
  File "proxmox.py", line 341, in <module>
    main()
  File "proxmox.py", line 312, in main
    if os.environ.has_key('PROXMOX_INVALID_CERT'):
AttributeError: '_Environ' object has no attribute 'has_key'
`

Then when I try to run it with python2 and get this error:

`
Traceback (most recent call last):
  File "proxmox.py", line 42, in <module>
    from ansible.module_utils.urls import open_url
ImportError: No module named ansible.module_utils.urls
`
That error probably occurs since ansible uses /usr/bin/python which is python3, so I end up with this script on python2 and ansible on python3.

**Comment by gardar** [comment]
Did some changes and got it to work on python3, submitted the changes as merge request #11

**Comment by vazhnov** [comment]
@gardar, could you, please, change code to have compatibility with both Python v2 and v3? Because of https://github.com/xezpeleta/Ansible-Proxmox-inventory/issues/12.

**Comment by gardar** [comment]
@vazhnov oh shoot I forgot to check the compatibility with v2. I'll see what I can do, but feel free to chime in.

**Comment by gardar** [comment]
> @gardar, could you, please, change code to have compatibility with both Python v2 and v3? Because of #12.

Just did a pull request #14 which should fix this, can you confirm?
