### ISSUE TITLE
Python 2.7 launch error

### ISSUE THREAD

**Issue by Uzzi** [xezpeleta/Ansible-Proxmox-inventory#12]
Hi, I'm on debian 9 with python 2.7 ansible 2.7
python proxmox.py --url=https://IP:8006/  --username=usr --password=psw --trust-invalid-certs --list --prett

output:
Traceback (most recent call last):
  File "proxmox.py", line 28, in <module>
    import urllib.request, urllib.parse, urllib.error
ImportError: No module named request

**Comment by vazhnov** [comment]
This is because of https://github.com/xezpeleta/Ansible-Proxmox-inventory/pull/11 which is connected to https://github.com/xezpeleta/Ansible-Proxmox-inventory/issues/10
