### ISSUE TITLE
Newbie question: why use this plugin? practical examples?

### ISSUE THREAD

**Issue by BarbzYHOOL** [xezpeleta/Ansible-Proxmox-inventory#13]
I have created role that creates containers and I have added a task that insert all the VMs IP and SSH ports in the inventory.

Can someone tell me why using this inventory plugin would be better/more practical? (never used any inventory plugin)

Any example?

**Comment by xezpeleta** [comment]
Hi @BarbzYHOOL 

This is a dynamic inventory, so every time you need to run Ansible on your hosts it will always get a fresh VM list from Proxmox using its API. More info about the advantages of inventory plugins here: https://docs.ansible.com/ansible/latest/user_guide/intro_dynamic_inventory.html

**Comment by BarbzYHOOL** [comment]
> If your Ansible inventory fluctuates over time, with hosts spinning up and shutting down in response to business demands,

I'm still not sure when to use this plugin though, no practical example?
