### ISSUE TITLE
TypeError: the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by Jungo495** [xezpeleta/Ansible-Proxmox-inventory#28]
Hi! Thanks for script, but i can't make it working:

`./proxmox.py --list Traceback (most recent call last): File "./proxmox.py", line 391, in <module> main() File "./proxmox.py", line 376, in main data = main_list(options, config_path) File "./proxmox.py", line 248, in main_list proxmox_api.auth() File "./proxmox.py", line 146, in auth validate_certs=self.options.validate)) File "/usr/lib/python3.5/json/__init__.py", line 268, in load parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw) File "/usr/lib/python3.5/json/__init__.py", line 312, in loads s.__class__.__name__)) TypeError: the JSON object must be str, not 'bytes'`

Python 3.5.3

**Comment by xezpeleta** [comment]
Are you still having this issue with the latest version?

Thanks
