### ISSUE TITLE
"proxmox_type" is not set for VMs

### ISSUE THREAD

**Issue by Twanislas** [xezpeleta/Ansible-Proxmox-inventory#34]
Hi,

Thanks for this very handy script !

I noticed that the field `proxmox_type` is not set on Qemu VMs, although it is set on LXC containers : `"proxmox_type": "lxc"`.

I was expecting it to look like `"proxmox_type": "qemu"` or something along those lines.

Cheers !

**Comment by xezpeleta** [comment]
Should be fixed now thanks to @maynero !
