### ISSUE TITLE
Inventory script under AWX 17.1.0 & 18.0.0

### ISSUE THREAD

**Issue by mYzk** [xezpeleta/Ansible-Proxmox-inventory#35]
Hi!

Has anyone had any luck on getting this to work under new AWX since they removed the custom script function from AWX?
Been trying to get this to work for a long time now and no luck so far.

Thank you!

**Comment by mYzk** [comment]
Update:

Got it working :) Works like a charm with AWX 18.0.0 and 19.0.0

**Comment by LukeMondy** [comment]
How did you get it working? Adding the python script repo as a Project, and then pointing the Inventory Source at the python script itself?
