### ISSUE TITLE
Question How it connects with VM?

### ISSUE THREAD

**Issue by giovannicandido** [xezpeleta/Ansible-Proxmox-inventory#4]
Hi,
I would like to know if the ip address of the vm has any effect on the playbook, if a vm is not in the same network as the machine running the playbook but only the proxmox server is accessible will it work?

In other words, this plugin either:

1 - Parse the IP address from the network attached to vm and use it as inventory target
2 - Connect direct to proxmox and run the commands in some particular way

What happens when there is more then one network?

I think this could be explained in the **readme**. I try to read the source but I'm quite not follow (not good on python :-)

Thanks. :+1:

**Comment by xezpeleta** [comment]
Hi @giovannicandido 

Good point. No, this inventory it's not using the VM IP address to connect. That would be interesting, but in Proxmox you only have the IP address information of LXC containers. KVM hosts network address isn't managed by Proxmox.

In fact it uses the VM name instead. So the only requirement is to set a VM name that you can resolve using DNS or your /etc/hosts. I will add that to the readme file.

By the way, it's not currently possible, but we could use the "Notes" field to overwrite the connection address. That would be cool. I'll add a feature request :)

Thanks!!

**Comment by giovannicandido** [comment]
Cristal clear now. Thanks
