### ISSUE TITLE
Submit improvements upstream

### ISSUE THREAD

**Issue by rtgibbons** [xezpeleta/Ansible-Proxmox-inventory#5]
Any thoughts, or previous effort, to get these change submitted to upstream? It would directly fix https://github.com/ansible/ansible/issues/18579

https://github.com/ansible/ansible/blob/devel/contrib/inventory/proxmox.py

**Comment by xezpeleta** [comment]
I didn't even try it, as this is not a custom fix, it's an alternative version which collects different fixes and improvements.

In fact, it includes code from PRs (like PR #17247) not merged by Ansible.
