### ISSUE TITLE
Does not work on new 8.0.3 Version 

### ISSUE THREAD

**Issue by rb-nk** [xezpeleta/Ansible-Proxmox-inventory#53]
Inventory call will fail on new Proxmox version 8.0.3.

Script throws string to float conversion exception: 

`[...]
proxmox.py", line 91, in get_version
return float(self['version'].split('-')[0]) ValueError: could not convert string to float: '8.0.3'`

This happens since there is no dash in this version string, therefore the return value is '8.0.3' which is no float. 
I'd suggest to split by dot to get the major version number, wich seems to be sufficiant to distinguish between api versions. 

Line 91 would look like this: 
`return float(self['version'].split('.')[0])`

Inventory script runs well for me after this little change.

**Comment by xezpeleta** [comment]
You're right, I'll apply this patch. If someday we need the minor number to distinguish between api version we can improve it with a regex.

Thanks!
