### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '8006api2'

### ISSUE THREAD

**Issue by mawa1213** [xezpeleta/Ansible-Proxmox-inventory#6]
Hi, I've tested the dynamic Inventory on my newly set up ansible node on proxmox 5.1 where I get the following error: 

```
root@ansible1:/etc/ansible# ./proxmox.py --url=https://192.168.52.245:8006 --username=root --password=XXXXXX --trust-invalid-certs --list
Traceback (most recent call last):
  File "./proxmox.py", line 332, in <module>
    main()
  File "./proxmox.py", line 317, in main
    data = main_list(options, config_path)
  File "./proxmox.py", line 203, in main_list
    proxmox_api.auth()
  File "./proxmox.py", line 138, in auth
    validate_certs=self.options.validate))
  File "/usr/lib/python2.7/dist-packages/ansible/module_utils/urls.py", line 793, in open_url
    ssl_handler = maybe_add_ssl_handler(url, validate_certs)
  File "/usr/lib/python2.7/dist-packages/ansible/module_utils/urls.py", line 761, in maybe_add_ssl_handler
    parsed = generic_urlparse(urlparse(url))
  File "/usr/lib/python2.7/dist-packages/ansible/module_utils/urls.py", line 401, in generic_urlparse
    generic_parts['port'] = parts.port
  File "/usr/lib/python2.7/urlparse.py", line 113, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: '8006api2'
```
I don't know if it's a problem with proxmox or python. OS on my ansible node is debian 9.

**Comment by xezpeleta** [comment]
Hi, thanks for your contribution. I didn't check it yet with Proxmox 5.x, but I guess we should do some changes in the code.

I'll try to take a look!

**Comment by mawa1213** [comment]
Thank you very much! I really appreciate your quick response.

**Comment by andor44** [comment]
This is not an API 5 error, this script works with 5.2 for me. You forgot to put a trailing slash at the end of your API url which causes the generated URL to be `http://foo:8006api2...`

Put a trailing slash after the port in your configuration.

@xezpeleta you might want to add a check into the script so it checks for trailing slash and if it's missing add it automatically.

**Comment by vazhnov** [comment]
I think this ticket should be closed.
If we need, let's open another one, with feature request.
