### ISSUE TITLE
Feature request: add multiple ways to resolve the VM IP address

### ISSUE THREAD

**Issue by xezpeleta** [xezpeleta/Ansible-Proxmox-inventory#8]
Currently we require resolvable VM names, as Proxmox cannot give us the VM's IP addresses.

It could be interesting to add the possibility to read the hostname / IP address vía the JSON code included in the Notes field, as we do with groups. Example:

```json
{ "ansible_host": "192.168.0.44","groups": ["utility", "databases"] }
```

**Comment by simonjgreen** [comment]
proxmox can supply the IP address if you have qemu tools running. it's supplied in the config item via the api (which this script is already grabbing, just not handling)

**Comment by vazhnov** [comment]
See other patch: https://github.com/Alex9779/Ansible-Proxmox-inventory/commit/e50a7a8009a37ea7bc1fb8ad0d1c6613570256dd

**Comment by vazhnov** [comment]
Ant another one variant, take info from [cloud-init](https://pve.proxmox.com/wiki/Cloud-Init_Support): https://github.com/b13f/Ansible-Proxmox-inventory/commit/290a45bb596e6ebc6858491dcc32c48987a9af63

**Comment by vikas027** [comment]
I have just made some changes to the script to report the IP Address instead of the hostnames. I have also removed LXC containers from the output.

https://raw.githubusercontent.com/vikas027/Ansible-Proxmox-inventory/myenv/proxmox.py

**Comment by davidcastellani** [comment]
It seems like @iTeV is onto something. If the ip address of a KVM is presented to the API for hosts with the `qemu-guest-agent` installed, the script could check for this via an API call and bring it into the inventory. If its blank, revert to the name of the VM as the hostname.

So the prereq for this to work is your KVM must have `qemu-guest-agent` installed on the machine. https://pve.proxmox.com/wiki/Qemu-guest-agent

If this first avenue does not work, by way of the API, maybe you can check for the `qemu-guest-agent` and resort to a CLI command to check for the eth0 IP address?

This is from my proxmox host, asking VMID 310 (rhel 7.4 with `qemu-guest-agent` installed) for its network configuration.

```
root@prox01:~# qm guest cmd 310 network-get-interfaces
[
   {
      "hardware-address" : "00:00:00:00:00:00",
      "ip-addresses" : [
         {
            "ip-address" : "127.0.0.1",
            "ip-address-type" : "ipv4",
            "prefix" : 8
         },
         {
            "ip-address" : "::1",
            "ip-address-type" : "ipv6",
            "prefix" : 128
         }
      ],
      "name" : "lo"
   },
   {
      "hardware-address" : "66:c8:4d:fd:10:3d",
      "ip-addresses" : [
         {
            "ip-address" : "172.16.1.111",
            "ip-address-type" : "ipv4",
            "prefix" : 24
         },
         {
            "ip-address" : "fe80::64c8:4dff:fefd:103d",
            "ip-address-type" : "ipv6",
            "prefix" : 64
         }
      ],
      "name" : "eth0"
   }
]
```

I think @iTeV API method is probably the best way to go. You could bring in eth0 as the ansible host and then maybe set a host_var for any additional interfaces and its IP.

**Comment by xezpeleta** [comment]
PR #21 is ready. Could you test it in your environment and check if it works?

Thanks

**Comment by iTeV** [comment]
Tested it. looks like it works flawlessly! `ansible_host` var is set for both LXC and KVM (if `qemu-guest` is installed).

One thing to keep in mind tough: What if a machine has 2 (or more) interfaces? How do we "tell" the script to fetch the IP-Address of that specific interface..

**Comment by xezpeleta** [comment]
> What if a machine has 2 (or more) interfaces? How do we "tell" the script to fetch the IP-Address of that specific interface..

The only solution comes to mind is to read the preferred interface name from the "_Notes_" field (JSON object), [just like we do with groups](https://github.com/xezpeleta/Ansible-Proxmox-inventory#tricks). Otherwise it will choose the first network interface (ignoring loopback interface).

```json
{ "groups": ["utility", "databases"], "network-interface": "eth0"}
```

I know, it's a little bit ugly to use _Notes_ field but I can't find a better solution. Personally I miss a Docker LABEL like feature in Proxmox, where you can specify multiple keys/values to the instances...

**Comment by h3po** [comment]
I have a dirty trick for getting IPs from vm without the agent. We can also get the vm config from the api and get the mac adresses. If the proxmox hosts themselves are part of the overall inventory, we can use a delegated task to lookup the hosts' ip address in the arp table.
Until now I haven't used a dynamic inventory, I did the mac address lookup inside the play using the proxmox_kvm task. Maybe it is possible to instead do this in the inventory script?
Here's a patch to proxmox.py to return the config: https://github.com/h3po/Ansible-Proxmox-inventory/commit/a0aca6bfca418dc28a0b0be03f8714f252b370fa

This is what I'm using currently:
```
---
- name: start vm
  proxmox_kvm:
    api_user: "{{proxmox_api_user}}"
    api_password: "{{proxmox_api_password}}"
    api_host: "{{proxmox_api_host}}"
    name: "{{vm_name}}"
    state: started
    timeout: 300
  retries: 2
  delay: 10
  register: tmp
  until: tmp is not failed
  delegate_to: localhost

- name: get the vm id from proxmox output
  set_fact: "vmid={{tmp.msg.split(' ')[1]}}"
  failed_when: not vmid.isdecimal()
  changed_when: false
  register: tmp

- name: get the mac address of the vm
  shell: "/usr/sbin/qm config {{vmid}} | awk '/net0/ { print tolower($2) }' | sed -r 's/[^=]*=([0-9a-f:]*),.*/\\1/g'"
  become: true
  delegate_to: "{{proxmox_node}}"
  changed_when: false
  register: tmp

- debug: "msg={{tmp.stdout}}"

- set_fact: "mac={{tmp.stdout}}"
  failed_when: not ((mac | length) == 17)

- name: get the ip address of the vm
  shell: "arp -an -i eth1 | grep '{{mac}}' | cut -d' ' -f2 | sed -r 's/\\((.*)\\)/\\1/g'"
  until: "('stdout' in tmp) and (tmp.stdout != '')"
  retries: 100
  delay: 5
  register: tmp
  delegate_to: "{{dhcp_host}}"
  changed_when: false

- debug: "msg={{tmp}}"

- set_fact: "vm_ip={{tmp.stdout}}"
  failed_when: not (vm_ip | ipaddr)
  changed_when: false

- debug: "msg={{vm_ip}}"
```

**Comment by h3po** [comment]
> PR #21 is ready. Could you test it in your environment and check if it works?
> 
> Thanks

I had a small problem with your PR, see https://github.com/xezpeleta/Ansible-Proxmox-inventory/pull/21#issuecomment-580727633

**Comment by xezpeleta** [comment]
> > PR #21 is ready. Could you test it in your environment and check if it works?
> > Thanks
> 
> I had a small problem with your PR, see [#21 (comment)](https://github.com/xezpeleta/Ansible-Proxmox-inventory/pull/21#issuecomment-580727633)

Thanks @h3po . I've applied your patch.
