### ISSUE TITLE
KeyError: 'template' with a Pool in Proxmox 5.3

### ISSUE THREAD

**Issue by stefanjay** [xezpeleta/Ansible-Proxmox-inventory#9]
Hi xepeleta,

proxmox version:
`            pve-manager/5.3-5/97ae681d (running kernel: 4.15.18-9-pve)`

I have the folloing issue using the proxmox.json config:
`root@awx:/etc/ansible# cat proxmox.json`

            {
                "url": "https://10.10.10.1:8006/",
                "username": "ansible@pam",
                "password": "abc",
                "validateCert": false
            } 

`root@awx:/etc/ansible# ./proxmox.py --list`

            Traceback (most recent call last):
              File "./proxmox.py", line 345, in <module>
                main()
              File "./proxmox.py", line 330, in main
                data = main_list(options, config_path)
              File "./proxmox.py", line 283, in main_list
                'hosts': proxmox_api.pool(pool).get_members_name(),
              File "./proxmox.py", line 94, in get_members_name
                return [member['name'] for member in self['members'] if member['template'] != 1]
            KeyError: 'template'

A ansible playbook for creating a vm on the prox host executed locally works excellent (using the api).

The net/ api is reachable via `telnet 10.10.10.1 8006:`
```
            root@awx:/etc/ansible# wget --no-check-certificate https://10.10.10.1:8006/api2/json/
            --2018-12-20 12:40:34--  https://10.10.10.1:8006/api2/json/
            Connecting to 10.10.10.1:8006... connected.
            The certificate's owner does not match hostname '10.10.10.1'
            HTTP request sent, awaiting response... 401 No ticket

            Username/Password Authentication Failed.
```

On my awx frontend I've implemented the script as Custom Inventory Script adding these three vars on line 103:

            options.url = "https://10.10.10.1:8006/"
            options.username = "ansible@pam"
            options.password = "abc"
And on line 317:

            bool_validate_cert = False
**On the frontend the scripts fails with the same error**

Response from the api log on the proxmox host:

`root@kvm01 /etc/pve/nodes/kvm01 # tailf /var/log/pveproxy/access.log |grep ansible`

     10.10.10.2 - ansible@pam [20/12/2018:12:43:11 +0100] "GET /api2/json/nodes HTTP/1.1" 200 338
     10.10.10.2 - ansible@pam [20/12/2018:12:43:11 +0100] "GET /api2/json/nodes/kvm01/qemu HTTP/1.1" 200 1951
     10.10.10.2 - ansible@pam [20/12/2018:12:43:11 +0100] "GET /api2/json/version HTTP/1.1" 200 78
     10.10.10.2 - ansible@pam [20/12/2018:12:43:11 +0100] "GET /api2/json/version HTTP/1.1" 200 78
     10.10.10.2 - ansible@pam [20/12/2018:12:43:11 +0100] "GET /api2/json/nodes/kvm01/lxc HTTP/1.1" 200 11
     10.10.10.2 - ansible@pam [20/12/2018:12:43:11 +0100] "GET /api2/json/version HTTP/1.1" 200 78
     10.10.10.2 - ansible@pam [20/12/2018:12:43:11 +0100] "GET /api2/json/version HTTP/1.1" 200 78
     10.10.10.2 - ansible@pam [20/12/2018:12:43:11 +0100] "GET /api2/json/nodes/kvm01/qemu/504/config HTTP/1.1" 200 446
     10.10.10.2 - ansible@pam [20/12/2018:12:43:11 +0100] "GET /api2/json/nodes/kvm01/qemu/502/config HTTP/1.1" 200 447
     10.10.10.2 - ansible@pam [20/12/2018:12:43:11 +0100] "GET /api2/json/nodes/kvm01/qemu/507/config HTTP/1.1" 200 513
     10.10.10.2 - ansible@pam [20/12/2018:12:43:11 +0100] "GET /api2/json/nodes/kvm01/qemu/501/config HTTP/1.1" 200 535
     10.10.10.2 - ansible@pam [20/12/2018:12:43:11 +0100] "GET /api2/json/nodes/kvm01/qemu/506/config HTTP/1.1" 200 470
     10.10.10.2 - ansible@pam [20/12/2018:12:43:11 +0100] "GET /api2/json/nodes/kvm01/qemu/503/config HTTP/1.1" 200 395
     10.10.10.2 - ansible@pam [20/12/2018:12:43:11 +0100] "GET /api2/json/nodes/kvm01/qemu/900/config HTTP/1.1" 200 529
     10.10.10.2 - ansible@pam [20/12/2018:12:43:11 +0100] "GET /api2/json/pools HTTP/1.1" 200 31
     10.10.10.2 - ansible@pam [20/12/2018:12:43:11 +0100] "GET /api2/json/pools/ansible HTTP/1.1" 200 2463

**Comment by stefanjay** [comment]
Update #1
commenting out line 94 to:
```

 class ProxmoxPool(dict):
     def get_members_name(self):
         print ""
         #return [member['name'] for member in self['members'] if member['vmid'] !=1]
```

Works on cli but not in awx:

RuntimeError: ansible-inventory failed (rc=1) with stdout:

     stderr:
      [WARNING]:  * Failed to parse /tmp/awx_187_qiQ7PK/tmpd7qa_C with script
     plugin: You defined a group 'ansible' with bad data for the host list:
         {u'hosts': None}

      [WARNING]: Unable to parse /tmp/awx_187_qiQ7PK/tmpd7qa_C as an inventory
     source

     ERROR! No inventory was parsed, please check your configuration and options.

**Comment by stefanjay** [comment]
Update #2 

Creating a Pool in Proxmox with vms, storages and permissions for the ansible user causes the script to fail. Commenting the line #94 in works as aspected.

The important part is:
     {u'hosts': None}

The script can't parse the pool inventory.

**Comment by Twanislas** [comment]
Hi !

FWIW, it works for me if I only add VMs or containers to my pools. Removing storage entitites fixes the issue.

Hope this helps :)

**Comment by Twanislas** [comment]
#16 should have fixed it.
